# Generated by Django 5.2.7 on 2025-10-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='created_ate',
            new_name='created_at',
        ),
    ]
